df <- read.table("c:\\dataset_11504_16.txt")
#str(df)
#mez <- bartlett.test (df, V1~V2)
#print(mez$p.value)
rez <-t.test(df$V1,df$v2,var.equal = F)
#rez <- wilcox.test (df$V1~df$V2)
sr1 <- mean(df$V1)
sr2 <- mean(df$V2)
print(sr1)
print(sr2)
print(rez$p.value)